-- Canonical raw email record. Immutable after ingest: it is the single source
-- of truth that replay, eval, and retrain reference, so it must never be
-- silently rewritten. Immutability is enforced by the database (below), not
-- merely by convention in application code.

create table emails (
    -- Canonical identifier, generated by the application at ingest.
    id              uuid        primary key,

    -- SHA-256 of raw_content; the idempotency key. A re-ingest of identical
    -- bytes collides here and returns the existing id rather than duplicating.
    content_hash    bytea       not null unique,

    -- Byte-faithful original message exactly as received.
    raw_content     bytea       not null,

    -- Parsed metadata downstream needs. Nullable because real-world headers are
    -- frequently missing or malformed; the raw_content remains authoritative.
    sender          text,
    sender_domain   text,
    recipients      text,
    subject         text,
    received_at     timestamptz,
    auth_results    text,

    -- Provenance of the ingest (api, seed loader, replay, ...).
    ingest_source   text        not null default 'api',
    ingested_at     timestamptz not null default now()
);

-- Sender identity is the partition/lookup key for reputation in later stories.
create index emails_sender_idx on emails (sender);
create index emails_sender_domain_idx on emails (sender_domain);

-- ---------------------------------------------------------------------------
-- Immutability enforcement
-- ---------------------------------------------------------------------------
-- Any UPDATE or DELETE on an emails row is rejected at the database. The
-- exception makes the attempt observable (it surfaces as a SQL error that the
-- application logs / a test can assert on) and guarantees no code path — not
-- even a buggy one — can mutate the canonical record.
create or replace function reject_emails_row_mutation() returns trigger as $$
begin
    raise exception 'emails is immutable: % on row % is not permitted',
        tg_op, coalesce(old.id::text, '<unknown>')
        using errcode = 'restrict_violation';
end;
$$ language plpgsql;

create trigger emails_reject_row_mutation
    before update or delete on emails
    for each row execute function reject_emails_row_mutation();

-- TRUNCATE bypasses row-level triggers, so block it with a statement trigger.
create or replace function reject_emails_truncate() returns trigger as $$
begin
    raise exception 'emails is immutable: TRUNCATE is not permitted'
        using errcode = 'restrict_violation';
end;
$$ language plpgsql;

create trigger emails_reject_truncate
    before truncate on emails
    for each statement execute function reject_emails_truncate();
